### ISSUE TITLE
yapi 1.6.2版本，按照插件后设置页面Swagger自动同步功能消失。

### ISSUE THREAD

**Issue by tenlee2012** [zgs225/yapi-plugin-dding#1]

**Comment by zgs225** [comment]
这个功能我没用过，具体在哪个页面？我去看看。

**Comment by tenlee2012** [comment]
最新1.7.0版本
项目详情页面的 【设置 】中，【Swagger自动同步功能】tab页 丢失了。
应该是https://github.com/zgs225/yapi-plugin-dding/blob/master/views/index.js
这个文件把已存在的tab覆盖了。

**Comment by zgs225** [comment]
嗯，应该是的。我会尽快修正。

**Comment by liaityong** [comment]
你好，这个问题修正了吗

**Comment by xianggeyouyu** [comment]
> 嗯，应该是的。我会尽快修正。

这个问题修正了吗

**Comment by zgs225** [comment]
哈哈，还没有。尴尬

**Comment by GreedyPirate** [comment]
我晕，我的也没了， @zgs225 还打算修复吗

**Comment by astonishqft** [comment]
> 我晕，我的也没了， @zgs225 还打算修复吗

https://github.com/zgs225/yapi-plugin-dding/pull/4
可以参考下这个方法

**Comment by astonishqft** [comment]
> > 嗯，应该是的。我会尽快修正。
> 
> 这个问题修正了吗

https://github.com/zgs225/yapi-plugin-dding/pull/4
可以参考下这个方法

**Comment by shenshihala** [comment]
还没修复

**Comment by zgs225** [comment]
已经修复了，请更新到 1.3.0
