### ISSUE TITLE
安装失败问题

### ISSUE THREAD

**Issue by acoldog** [zgs225/yapi-plugin-dding#10]
@zgs225 [https://github.com/zgs225/yapi-plugin-dding/issues/8](url)

跟这个碰到一样的问题，大佬能不能说一下当前插件可以支持哪个yapi的版本

**Comment by zgs225** [comment]
我更新了一个 1.3.0 版本，支持了最新的 yapi，你可以更新试试

**Comment by acoldog** [comment]
@zgs225 拉了你昨晚发的版本重装还是安装失败 报一样的错误

**Comment by zgs225** [comment]
这个错误是 yapi 本身造成的。

React 从 16.9.0 版本开始将 componentWillReceiveProps 废弃了。yapi 中引用的 react 版本是 “^16.2.0”。这种引用方式会自动升级次要版本，所以会报这个错误。

我这边的解决方式是在 vendors 目录中手动安装一个低版本的 react，比如：yarn add react@16.2.0

**Comment by llb1020** [comment]
@zgs225 通过yarn add react@16.2.0 指定版本安装后，报UNMET PEER DEPENDENCY react@16.2.0
大神是否可以制作一个docker镜像，包含了一些常用的插件？我看你之前做过的docker镜像，只是一个node执行安装插件的。是否可以做一个完整点的镜像？

**Comment by zgs225** [comment]
> @zgs225 通过yarn add react@16.2.0 指定版本安装后，报UNMET PEER DEPENDENCY react@16.2.0
> 大神是否可以制作一个docker镜像，包含了一些常用的插件？我看你之前做过的docker镜像，只是一个node执行安装插件的。是否可以做一个完整点的镜像？

你可以检查一下你的 yapi 里面 react 的依赖情况。这种问题一般出现都是因为有多个不同的包依赖不同版本的 react 造成的。
