### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by well-monkey** [zgs225/yapi-plugin-dding#2]
本地不能添加么

**Comment by well-monkey** [comment]
log: yapi-plugin-dingding: 开始运行
log: yapi-plugin-dingding: 已推送。

**Comment by zgs225** [comment]
什么意思？有更完整的错误信息吗？本地应该没问题的，我开始是在本地呀。

**Comment by well-monkey** [comment]
本地运行 添加钉钉 机器人 
log显示 消息已推送  
但还是报错  connect ECONNREFUSED 127.0.0.1:80   
等于我在本地运行的环境中已经修改了相关接口 但是并没有推送到钉钉群中。不清楚原因

**Comment by zgs225** [comment]
你是 yapi 是哪个版本的？

**Comment by well-monkey** [comment]
v1.7.0

**Comment by zgs225** [comment]
你是不是没有添加配置

**Comment by well-monkey** [comment]
配置添加了发生在添加配置后

**Comment by whattomjerry** [comment]
> 
> 
> 配置添加了发生在添加配置后

老铁遇到一样的问题  你的问题解决了吗  怎么解决的？
