### ISSUE TITLE
安装插件失败，消息发不出去

### ISSUE THREAD

**Issue by LauJon** [zgs225/yapi-plugin-dding#5]
![image](https://user-images.githubusercontent.com/26211318/69134590-b13ab700-0af2-11ea-82b3-898dc5cbd1f2.png)
![image](https://user-images.githubusercontent.com/26211318/69134612-bdbf0f80-0af2-11ea-9b58-bcb5fec8d70c.png)

**Comment by xiazhenyou** [comment]
npx react-codemod rename-unsafe-lifecycles --force
紧接着输入报错js所在的文件夹
然后选择JavaScript with Flow，如下图
![image](https://user-images.githubusercontent.com/58844127/70887670-76f10680-2019-11ea-9680-3cf0b576431f.png)
![image](https://user-images.githubusercontent.com/58844127/70887697-87a17c80-2019-11ea-9516-b1b23252516c.png)

**Comment by LauJon** [comment]
> npx react-codemodname-unsafe-lifecycles --force
> 紧接着输入报错js所在的文件夹
> 然后用Flow选择JavaScript，如下图
> ![图片](https://user-images.githubusercontent.com/58844127/70887670-76f10680-2019-11ea-9680-3cf0b576431f.png)
> ![图片](https://user-images.githubusercontent.com/58844127/70887697-87a17c80-2019-11ea-9516-b1b23252516c.png)

**Comment by LauJon** [comment]
![image](https://user-images.githubusercontent.com/26211318/71861501-89022880-3131-11ea-971a-30f0ce9e661f.png)
![image](https://user-images.githubusercontent.com/26211318/71861512-915a6380-3131-11ea-9109-21d63222f35c.png)
